/***
 * Project: DryBox Control
 * File   : HeatingData.h
 * Author : Werner Riemann 
 * Created: 08.05.2024
 * Board: Arduino Nano
 * 
 * Description: Definition of Class HeatingData
 *              Class for handling the values for heating power and heater fan speed
 *              depending on the different temperature ranges
 * 
 */

 #include <stdint.h>
 #include <Arduino.h>

class HeatingData
{

private:
/* data */


public:
/* data */
uint8_t rampUpHeatPWM[3];                 // ramp will be generated by software on calling range setup
uint8_t defaultHeaterPWM;
uint8_t defaultHeaterFanPWM;
uint8_t nearDestHeaterPWM;
uint8_t lowHeaterFanPWM;
uint8_t turboHeaterPWM;
uint8_t turboHeaterFanPWM;
float compareOffset;
float compareOffsetTurboMode;
uint8_t ventilationHeaterPWM;
uint8_t ventilationHeaterFanPWM;
uint8_t ventilationFanPWN;
uint8_t airExtractionTime;
uint8_t finalAirExtractionTime;
uint8_t airExchangeIntervallMinutes;

/* Methods */
HeatingData();

void SetupHeatingValues(int dryDestTemp);

};